package models.foraging;

public enum ForagingSeedsTypes {
    Jazzseeds(),
    Carrotseeds(),
    Cauliflowerseeds(),
    CoffeeBean(),
    Garlicseeds(),
    BeanStarter(),
    Kaleseeds(),
    Parsnipseeds(),
    Potatoseeds(),
    Rhubarbseeds(),
    Strawberryseeds(),
    TulipBulb(),
    RiceShoot(),
    Blueberryseeds(),
    Cornseeds(),
    HopsStarter(),
    Pepperseeds(),
    Melonseeds(),
    Poppyseeds(),
    Radishseeds(),
    RedCabbageseeds(),
    Starfruitseeds(),
    Spangleseeds(),
    SummerSquashseeds(),
    Sunflowerseeds(),
    Tomatoseeds(),
    Wheatseeds(),
    Amaranthseeds(),
    Artichokeseeds(),
    Beetseeds(),
    BokChoyseeds(),
    Broccoliseeds(),
    Cranberryseeds(),
    Eggplantseeds(),
    Fairyseeds(),
    GrapeStarter(),
    Pumpkinseeds(),
    Yamseeds(),
    RareSeed(),
    Powdermelonseeds(),
    Ancientseeds(),
    Mixedseeds();

    public String getName() {
        return name();
    }
}
