package com.stardew.network;

public enum MessageType {
    REGISTER_INITIAL,
    REGISTER_RESULT,
    REGISTER_FINALLY,
    LOGIN,
    LOGIN_RESULT,
    GET_SECURITY_QUESTION,
    GET_SECURITY_QUESTION_RESULT,
    FORGET_PASSWORD,
    FORGET_PASSWORD_RESULT,
    CREATE_LOBBY,
    CREATE_LOBBY_RESULT,
    SEND_LOBBIES,
    SEND_LOBBIES_RESULT,
}
